
struct keymap g_binds[] = {
	{ SDL_SCANCODE_X, RETRO_DEVICE_ID_JOYPAD_A },
	{ SDL_SCANCODE_Z, RETRO_DEVICE_ID_JOYPAD_B },
	{ SDL_SCANCODE_A, RETRO_DEVICE_ID_JOYPAD_Y },
	{ SDL_SCANCODE_S, RETRO_DEVICE_ID_JOYPAD_X },
	{ SDL_SCANCODE_Q, RETRO_DEVICE_ID_JOYPAD_L },
	{ SDL_SCANCODE_W, RETRO_DEVICE_ID_JOYPAD_R },
	{ SDL_SCANCODE_UP, RETRO_DEVICE_ID_JOYPAD_UP },
	{ SDL_SCANCODE_DOWN, RETRO_DEVICE_ID_JOYPAD_DOWN },
	{ SDL_SCANCODE_LEFT, RETRO_DEVICE_ID_JOYPAD_LEFT },
	{ SDL_SCANCODE_RIGHT, RETRO_DEVICE_ID_JOYPAD_RIGHT },
	{ SDL_SCANCODE_RETURN, RETRO_DEVICE_ID_JOYPAD_START },
	{ SDL_SCANCODE_BACKSPACE, RETRO_DEVICE_ID_JOYPAD_SELECT },
	{ SDL_SCANCODE_I, RETRO_DEVICE_ID_JOYPAD_L2 },
	{ SDL_SCANCODE_O, RETRO_DEVICE_ID_JOYPAD_R2 },
	{ 0, 0 }
};

struct keymap g_kbinds[] = {
{RETROK_BACKSPACE      ,SDLK_BACKSPACE},//8,
{RETROK_TAB            ,SDLK_TAB},//9,
{RETROK_CLEAR          ,SDLK_CLEAR},//12,
{RETROK_RETURN         ,SDLK_RETURN},//13,
{RETROK_PAUSE          ,SDLK_PAUSE},//19,
{RETROK_ESCAPE         ,SDLK_ESCAPE},//27,
{RETROK_SPACE          ,SDLK_SPACE},//32,
{RETROK_EXCLAIM        ,SDLK_EXCLAIM},//33,
{RETROK_QUOTEDBL       ,SDLK_QUOTEDBL},//34,
{RETROK_HASH           ,SDLK_HASH},//35,
{RETROK_DOLLAR         ,SDLK_DOLLAR},//36,
{RETROK_AMPERSAND      ,SDLK_AMPERSAND},//38,
{RETROK_QUOTE          ,SDLK_QUOTE},//39,
{RETROK_LEFTPAREN      ,SDLK_LEFTPAREN},//40,
{RETROK_RIGHTPAREN     ,SDLK_RIGHTPAREN},//41,
{RETROK_ASTERISK       ,SDLK_ASTERISK},//42,
{RETROK_PLUS           ,SDLK_PLUS},//43,
{RETROK_COMMA          ,SDLK_COMMA},//44,
{RETROK_MINUS          ,SDLK_MINUS},//45,
{RETROK_PERIOD         ,SDLK_PERIOD},//46,
{RETROK_SLASH          ,SDLK_SLASH},//47,
{RETROK_0              ,SDLK_0},//48,
{RETROK_1              ,SDLK_1},//49,
{RETROK_2              ,SDLK_2},//50,
{RETROK_3              ,SDLK_3},//51,
{RETROK_4              ,SDLK_4},//52,
{RETROK_5              ,SDLK_5},//53,
{RETROK_6              ,SDLK_6},//54,
{RETROK_7              ,SDLK_7},//55,
{RETROK_8              ,SDLK_8},//56,
{RETROK_9              ,SDLK_9},//57,
{RETROK_COLON          ,SDLK_COLON},//58,
{RETROK_SEMICOLON      ,SDLK_SEMICOLON},//59,
{RETROK_LESS           ,SDLK_LESS},//60,
{RETROK_EQUALS         ,SDLK_EQUALS},//61,
{RETROK_GREATER        ,SDLK_GREATER},//62,
{RETROK_QUESTION       ,SDLK_QUESTION},//63,
{RETROK_AT             ,SDLK_AT},//64,
{RETROK_LEFTBRACKET    ,SDLK_LEFTBRACKET},//91,
{RETROK_BACKSLASH      ,SDLK_BACKSLASH},//92,
{RETROK_RIGHTBRACKET   ,SDLK_RIGHTBRACKET},//93,
{RETROK_CARET          ,SDLK_CARET},//94,
{RETROK_UNDERSCORE     ,SDLK_UNDERSCORE},//95,
{RETROK_BACKQUOTE      ,SDLK_BACKQUOTE},//96,
{RETROK_a              ,SDLK_a},//97,
{RETROK_b              ,SDLK_b},//98,
{RETROK_c              ,SDLK_c},//99,
{RETROK_d              ,SDLK_d},//100,
{RETROK_e              ,SDLK_e},//101,
{RETROK_f              ,SDLK_f},//102,
{RETROK_g              ,SDLK_g},//103,
{RETROK_h              ,SDLK_h},//104,
{RETROK_i              ,SDLK_i},//105,
{RETROK_j              ,SDLK_j},//106,
{RETROK_k              ,SDLK_k},//107,
{RETROK_l              ,SDLK_l},//108,
{RETROK_m              ,SDLK_m},//109,
{RETROK_n              ,SDLK_n},//110,
{RETROK_o              ,SDLK_o},//111,
{RETROK_p              ,SDLK_p},//112,
{RETROK_q              ,SDLK_q},//113,
{RETROK_r              ,SDLK_r},//114,
{RETROK_s              ,SDLK_s},//115,
{RETROK_t              ,SDLK_t},//116,
{RETROK_u              ,SDLK_u},//117,
{RETROK_v              ,SDLK_v},//118,
{RETROK_w              ,SDLK_w},//119,
{RETROK_x              ,SDLK_x},//120,
{RETROK_y              ,SDLK_y},//121,
{RETROK_z              ,SDLK_z},//122,
{RETROK_DELETE         ,SDLK_DELETE},//127,
{RETROK_KP0            ,SDLK_KP_0},//256,
{RETROK_KP1            ,SDLK_KP_1},//257,
{RETROK_KP2            ,SDLK_KP_2},//258,
{RETROK_KP3            ,SDLK_KP_3},//259,
{RETROK_KP4            ,SDLK_KP_4},//260,
{RETROK_KP5            ,SDLK_KP_5},//261,
{RETROK_KP6            ,SDLK_KP_6},//262,
{RETROK_KP7            ,SDLK_KP_7},//263,
{RETROK_KP8            ,SDLK_KP_8},//264,
{RETROK_KP9            ,SDLK_KP_9},//265,
{RETROK_KP_PERIOD      ,SDLK_KP_PERIOD},//266,
{RETROK_KP_DIVIDE      ,SDLK_KP_DIVIDE},//267,
{RETROK_KP_MULTIPLY    ,SDLK_KP_MULTIPLY},//268,
{RETROK_KP_MINUS       ,SDLK_KP_MINUS},//269,
{RETROK_KP_PLUS        ,SDLK_KP_PLUS},//270,
{RETROK_KP_ENTER       ,SDLK_KP_ENTER},//271,
{RETROK_KP_EQUALS      ,SDLK_KP_EQUALS},//272,
{RETROK_UP             ,SDLK_UP},//273,
{RETROK_DOWN           ,SDLK_DOWN},//274,
{RETROK_RIGHT          ,SDLK_RIGHT},//275,
{RETROK_LEFT           ,SDLK_LEFT},//276,
{RETROK_INSERT         ,SDLK_INSERT},//277,
{RETROK_HOME           ,SDLK_HOME},//278,
{RETROK_END            ,SDLK_END},//279,
{RETROK_PAGEUP         ,SDLK_PAGEUP},//280,
{RETROK_PAGEDOWN       ,SDLK_PAGEDOWN},//281,
{RETROK_F1             ,SDLK_F1},//282,
{RETROK_F2             ,SDLK_F2},//283,
{RETROK_F3             ,SDLK_F3},//284,
{RETROK_F4             ,SDLK_F4},//285,
{RETROK_F5             ,SDLK_F5},//286,
{RETROK_F6             ,SDLK_F6},//287,
{RETROK_F7             ,SDLK_F7},//288,
{RETROK_F8             ,SDLK_F8},//289,
{RETROK_F9             ,SDLK_F9},//290,
{RETROK_F10            ,SDLK_F10},//291,
{RETROK_F11            ,SDLK_F11},//292,
{RETROK_F12            ,SDLK_F12},//293,
{RETROK_F13            ,SDLK_F13},//294,
{RETROK_F14            ,SDLK_F14},//295,
{RETROK_F15            ,SDLK_F15},//296,
{RETROK_NUMLOCK        ,SDLK_NUMLOCKCLEAR},//300,
{RETROK_CAPSLOCK       ,SDLK_CAPSLOCK},//301,
{RETROK_SCROLLOCK      ,SDLK_SCROLLLOCK},//302,
{RETROK_RSHIFT         ,SDLK_RSHIFT},//303,
{RETROK_LSHIFT         ,SDLK_LSHIFT},//304,
{RETROK_RCTRL          ,SDLK_RCTRL},//305,
{RETROK_LCTRL          ,SDLK_LCTRL},//306,
{RETROK_RALT           ,SDLK_RALT},//307,
{RETROK_LALT           ,SDLK_LALT},//308,
{RETROK_RMETA          ,SDLK_RGUI},//309,
{RETROK_LMETA          ,SDLK_LGUI},//310,
{RETROK_LSUPER         ,SDLK_LGUI},//311,
{RETROK_RSUPER         ,SDLK_RGUI},//312,
{RETROK_MODE           ,SDLK_MODE},//313,
{RETROK_COMPOSE        ,SDLK_APPLICATION},//314,
{RETROK_HELP           ,SDLK_HELP},//315,
{RETROK_PRINT          ,SDLK_PRINTSCREEN},//316,
{RETROK_SYSREQ         ,SDLK_SYSREQ},//317,
{RETROK_BREAK          ,SDLK_STOP},//318,
{RETROK_MENU           ,SDLK_MENU},//319,
{RETROK_POWER          ,SDLK_POWER},//320,
{RETROK_EURO           ,SDLK_UNKNOWN},//321,
{RETROK_UNDO           ,SDLK_UNDO},//322,
	{ 0, 0 }
};